name: Bump version
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bump version in package.json
        run: npm version minor
      - name: Push changes
        run: |
          git config --global user.name 'simon04PL'
          git config --global user.email 'szymon.msa@gmail.com'
          git push --follow-tags
      - name: Bump version and push tag
        uses: undergroundwires/bump-everywhere@master
        with:
          repository: ${{ github.repository }}
          user: ${{ github.actor }}
          git-token: ${{ secrets.PAT }}
          release-type: 'none'

